[agent]
  interval       = "10s"
  flush_interval = "10s"
  hostname       = "kafka-consumer"

[[inputs.kafka_consumer]]
  brokers            = ["kafka.snmp-monitor.svc.cluster.local:9092"]
  topics             = ["snmp-metrics"]
  consumer_group     = "timescaledb-writer"
  offset             = "oldest"
  data_format        = "json"
  json_name_key      = "name"
  json_time_key      = "timestamp"
  json_time_format   = "unix"
  json_string_fields = ["fields_sysName","fields_sysDescr","fields_cpuUsage","fields_memUsage","fields_optRxPower","fields_optTxPower","fields_chassisTemp","fields_bgpPeers","tags_source"]
  tag_keys           = ["host"]

[[processors.rename]]
  [[processors.rename.replace]]
    field = "fields_sysName"
    dest  = "sysName"
  [[processors.rename.replace]]
    field = "fields_sysDescr"
    dest  = "sysDescr"
  [[processors.rename.replace]]
    field = "fields_cpuUsage"
    dest  = "cpuUsage"
  [[processors.rename.replace]]
    field = "fields_memUsage"
    dest  = "memUsage"
  [[processors.rename.replace]]
    field = "fields_sysUpTime"
    dest  = "sysUpTime"
  [[processors.rename.replace]]
    field = "fields_optRxPower"
    dest  = "optRxPower"
  [[processors.rename.replace]]
    field = "fields_optTxPower"
    dest  = "optTxPower"
  [[processors.rename.replace]]
    field = "fields_chassisTemp"
    dest  = "chassisTemp"
  [[processors.rename.replace]]
    field = "fields_bgpPeers"
    dest  = "bgpPeers"
  [[processors.rename.replace]]
    field = "fields_ifInOctets"
    dest  = "ifInOctets"
  [[processors.rename.replace]]
    field = "fields_ifOutOctets"
    dest  = "ifOutOctets"
  [[processors.rename.replace]]
    field = "tags_source"
    dest  = "source"

[[outputs.postgresql]]
  connection           = "host=timescaledb.snmp-monitor.svc.cluster.local dbname=snmp_metrics user=telegraf password=telegraf123"
  schema               = "public"
  tags_as_foreign_keys = false
  create_templates     = ['''CREATE TABLE IF NOT EXISTS {{ .table }} ({{ .columns }})''']
