agentAddress udp:0.0.0.0:161
rocommunity public 0.0.0.0/0
sysDescr Arista Networks EOS version 4.29.2F running on DCS-7050TX-64
sysContact noc-vivo@telefonica.com
extend cpuUsage    /bin/sh -c "echo $((RANDOM % 30 + 10))"
extend memUsage    /bin/sh -c "echo $((RANDOM % 40 + 20))"
extend ifInOctets  /bin/sh -c "v=$((RANDOM * RANDOM)); echo ${v#-}"
extend ifOutOctets /bin/sh -c "v=$((RANDOM * RANDOM)); echo ${v#-}"
view all included .1
access notConfigGroup "" any noauth exact all all none
