agentAddress udp:0.0.0.0:161
rocommunity public 0.0.0.0/0
sysDescr Cisco IOS XR Software Version 7.9.2 ASR-9001 chassis
sysContact noc-vivo@telefonica.com
extend cpuUsage    /bin/sh -c "echo $((RANDOM % 45 + 15))"
extend memUsage    /bin/sh -c "echo $((RANDOM % 35 + 30))"
extend bgpPeers    /bin/sh -c "echo $((RANDOM % 10 + 20))"
extend ifInOctets  /bin/sh -c "v=$((RANDOM * RANDOM)); echo ${v#-}"
extend ifOutOctets /bin/sh -c "v=$((RANDOM * RANDOM)); echo ${v#-}"
view all included .1
access notConfigGroup "" any noauth exact all all none
