agentAddress udp:0.0.0.0:161
rocommunity public 0.0.0.0/0
sysDescr Ciena 6500 Packet-Optical Platform SW Release 14.1.0.GA
sysContact noc-vivo@telefonica.com
extend optRxPower  /bin/sh -c "echo $(( -(RANDOM % 300 + 200) ))"
extend optTxPower  /bin/sh -c "echo $(( -(RANDOM % 100 + 10) ))"
extend chassisTemp /bin/sh -c "echo $((RANDOM % 20 + 35))"
extend cpuUsage    /bin/sh -c "echo $((RANDOM % 20 + 5))"
extend memUsage    /bin/sh -c "echo $((RANDOM % 25 + 40))"
view all included .1
access notConfigGroup "" any noauth exact all all none
