agentAddress udp:0.0.0.0:161
rocommunity public 0.0.0.0/0
sysDescr Huawei Versatile Routing Platform VRP Version 8.220 (NE40E V800R011C10SPC607)
sysContact noc-vivo@telefonica.com
extend cpuUsage    /bin/sh -c "echo $((RANDOM % 35 + 10))"
extend memUsage    /bin/sh -c "echo $((RANDOM % 40 + 25))"
extend ifInOctets  /bin/sh -c "v=$((RANDOM * RANDOM)); echo ${v#-}"
extend ifOutOctets /bin/sh -c "v=$((RANDOM * RANDOM)); echo ${v#-}"
view all included .1
access notConfigGroup "" any noauth exact all all none
